import * as ts from "../tsgo/ts";
// flattened compiler exports, now backed by tsgo
import {
  type CompilerOptions,
  DiagnosticCategory,
  type EditorSettings,
  EmitHint,
  type ImportPhaseModifierSyntaxKind,
  LanguageVariant,
  ModuleKind,
  ModuleResolutionKind,
  NewLineKind,
  NodeFlags,
  ObjectFlags,
  ScriptKind,
  ScriptTarget,
  SymbolFlags,
  SyntaxKind,
  TypeFlags,
  TypeFormatFlags,
} from "../tsgo/ts";
export {
  type CompilerOptions,
  DiagnosticCategory,
  type EditorSettings,
  EmitHint,
  type ImportPhaseModifierSyntaxKind,
  LanguageVariant,
  ModuleKind,
  ModuleResolutionKind,
  NewLineKind,
  NodeFlags,
  ObjectFlags,
  ScriptKind,
  ScriptTarget,
  SymbolFlags,
  SyntaxKind,
  ts,
  TypeFlags,
  TypeFormatFlags,
};
