import * as ts from "typescript";
// flattened typescript exports
import {
  type CompilerOptions,
  DiagnosticCategory,
  type EditorSettings,
  EmitHint,
  type ImportPhaseModifierSyntaxKind,
  LanguageVariant,
  ModuleKind,
  ModuleResolutionKind,
  NewLineKind,
  NodeFlags,
  ObjectFlags,
  ScriptKind,
  ScriptTarget,
  SymbolFlags,
  SyntaxKind,
  TypeFlags,
  TypeFormatFlags,
} from "typescript";
export {
  type CompilerOptions,
  DiagnosticCategory,
  type EditorSettings,
  EmitHint,
  type ImportPhaseModifierSyntaxKind,
  LanguageVariant,
  ModuleKind,
  ModuleResolutionKind,
  NewLineKind,
  NodeFlags,
  ObjectFlags,
  ScriptKind,
  ScriptTarget,
  SymbolFlags,
  SyntaxKind,
  ts,
  TypeFlags,
  TypeFormatFlags,
};
