import * as ts from "typescript";
import * as compiler from "./../compiler";

// when changing this, make sure to run `npm run code-generate`.
// that will automatically update all other parts of the application that need to be updated when this changes.

// using an "any" type here because I couldn't figure out a way of getting the typescript compiler to understand this
export const nodeToWrapperMappings: { [key: number]: any } = {
    [ts.SyntaxKind.SourceFile]: compiler.SourceFile,
    [ts.SyntaxKind.ArrayLiteralExpression]: compiler.ArrayLiteralExpression,
    [ts.SyntaxKind.CallExpression]: compiler.CallExpression,
    [ts.SyntaxKind.ClassDeclaration]: compiler.ClassDeclaration,
    [ts.SyntaxKind.Constructor]: compiler.ConstructorDeclaration,
    [ts.SyntaxKind.ConstructSignature]: compiler.ConstructSignatureDeclaration,
    [ts.SyntaxKind.ComputedPropertyName]: compiler.ComputedPropertyName,
    [ts.SyntaxKind.Decorator]: compiler.Decorator,
    [ts.SyntaxKind.EnumDeclaration]: compiler.EnumDeclaration,
    [ts.SyntaxKind.EnumMember]: compiler.EnumMember,
    [ts.SyntaxKind.ExportDeclaration]: compiler.ExportDeclaration,
    [ts.SyntaxKind.ExportSpecifier]: compiler.ExportSpecifier,
    [ts.SyntaxKind.ExpressionWithTypeArguments]: compiler.ExpressionWithTypeArguments,
    [ts.SyntaxKind.FunctionDeclaration]: compiler.FunctionDeclaration,
    [ts.SyntaxKind.FunctionExpression]: compiler.FunctionExpression,
    [ts.SyntaxKind.GetAccessor]: compiler.GetAccessorDeclaration,
    [ts.SyntaxKind.HeritageClause]: compiler.HeritageClause,
    [ts.SyntaxKind.Identifier]: compiler.Identifier,
    [ts.SyntaxKind.ImportDeclaration]: compiler.ImportDeclaration,
    [ts.SyntaxKind.ImportSpecifier]: compiler.ImportSpecifier,
    [ts.SyntaxKind.InterfaceDeclaration]: compiler.InterfaceDeclaration,
    [ts.SyntaxKind.MethodDeclaration]: compiler.MethodDeclaration,
    [ts.SyntaxKind.MethodSignature]: compiler.MethodSignature,
    [ts.SyntaxKind.ModuleDeclaration]: compiler.NamespaceDeclaration,
    [ts.SyntaxKind.NumericLiteral]: compiler.NumericLiteral,
    [ts.SyntaxKind.FirstLiteralToken]: compiler.NumericLiteral,
    [ts.SyntaxKind.ObjectLiteralExpression]: compiler.ObjectLiteralExpression,
    [ts.SyntaxKind.Parameter]: compiler.ParameterDeclaration,
    [ts.SyntaxKind.PropertyAccessExpression]: compiler.PropertyAccessExpression,
    [ts.SyntaxKind.PropertyAssignment]: compiler.PropertyAssignment,
    [ts.SyntaxKind.PropertyDeclaration]: compiler.PropertyDeclaration,
    [ts.SyntaxKind.PropertySignature]: compiler.PropertySignature,
    [ts.SyntaxKind.QualifiedName]: compiler.QualifiedName,
    [ts.SyntaxKind.FirstNode]: compiler.QualifiedName,
    [ts.SyntaxKind.RegularExpressionLiteral]: compiler.RegularExpressionLiteral,
    [ts.SyntaxKind.SetAccessor]: compiler.SetAccessorDeclaration,
    [ts.SyntaxKind.ShorthandPropertyAssignment]: compiler.ShorthandPropertyAssignment,
    [ts.SyntaxKind.SpreadAssignment]: compiler.SpreadAssignment,
    [ts.SyntaxKind.StringLiteral]: compiler.StringLiteral,
    [ts.SyntaxKind.SyntaxList]: compiler.SyntaxList,
    [ts.SyntaxKind.TypeAliasDeclaration]: compiler.TypeAliasDeclaration,
    [ts.SyntaxKind.TypeParameter]: compiler.TypeParameterDeclaration,
    [ts.SyntaxKind.TypeReference]: compiler.TypeReferenceNode,
    [ts.SyntaxKind.VariableDeclaration]: compiler.VariableDeclaration,
    [ts.SyntaxKind.VariableStatement]: compiler.VariableStatement,
    [ts.SyntaxKind.JSDocComment]: compiler.JSDoc,
    [ts.SyntaxKind.FirstTypeNode]: compiler.TypeNode,
    [ts.SyntaxKind.LastTypeNode]: compiler.TypeNode,
    [ts.SyntaxKind.JSDocTag]: compiler.JSDocUnknownTag,
    [ts.SyntaxKind.JSDocAugmentsTag]: compiler.JSDocAugmentsTag,
    [ts.SyntaxKind.JSDocClassTag]: compiler.JSDocClassTag,
    [ts.SyntaxKind.JSDocReturnTag]: compiler.JSDocReturnTag,
    [ts.SyntaxKind.JSDocTypeTag]: compiler.JSDocTypeTag,
    [ts.SyntaxKind.JSDocTypedefTag]: compiler.JSDocTypedefTag,
    [ts.SyntaxKind.JSDocPropertyTag]: compiler.JSDocPropertyTag
};
