import { folders, path, tsMorph } from "./deps.ts";
const { Node, Project } = tsMorph;

const project = new Project();
const folderPath = "./dist-deno";
const fileSystem = project.getFileSystem();

const commonFile = project.addSourceFileAtPath(`${folderPath}/ts-morph-common.js`);

updateTypeScriptImportsExports(commonFile);

commonFile.insertImportDeclarations(0, [{
  moduleSpecifier: "./DenoRuntime.ts",
  namedImports: ["DenoRuntime"],
}]);
commonFile.getClassOrThrow("NodeRuntime").remove();
commonFile.getClassOrThrow("NodeRuntimeFileSystem").remove();
commonFile.getClassOrThrow("NodeRuntimePath").remove();
commonFile.getClassOrThrow("BrowserRuntime").remove();
commonFile.getClassOrThrow("BrowserRuntimeFileSystem").remove();
commonFile.getClassOrThrow("BrowserRuntimePath").remove();
commonFile.getFunctionOrThrow("isNodeJs").remove();
commonFile.getImportDeclarationOrThrow("node:path").remove();
commonFile.getImportDeclarationOrThrow("minimatch").remove();
commonFile.getImportDeclarationOrThrow("tinyglobby").remove();
commonFile.getImportDeclarationOrThrow("node:os").remove();
commonFile.getImportDeclarationOrThrow("node:fs").remove();
commonFile.getImportDeclarationOrThrow("node:fs/promises").remove();
commonFile.getImportDeclarationOrThrow("path-browserify").remove();

const runtimeFileDestinationPath = `${folderPath}/DenoRuntime.ts`;
const runtimeFullText = fileSystem.readFileSync("./src/runtimes/DenoRuntime.ts");
fileSystem.writeFileSync(runtimeFileDestinationPath, runtimeFullText.replace(/\/\/ @ts\-ignore(\s|(\r?\n))*/g, ""));
const runtimeSourceFile = project.addSourceFileAtPath(runtimeFileDestinationPath);
runtimeSourceFile.getVariableDeclarationOrThrow("Deno").remove();
runtimeSourceFile.saveSync();

const packageJson = JSON.parse(fileSystem.readFileSync("./package.json"));

// setup the deno runtime
commonFile.getFunctionOrThrow("getRuntime").setBodyText("return new DenoRuntime();");
commonFile.saveSync();

const copyDirPath = "../../deno/common/";
fileSystem.mkdirSync(copyDirPath);
fileSystem.copySync(`${folderPath}/ts-morph-common.js`, `${copyDirPath}/ts_morph_common.js`);
fileSystem.copySync(`${folderPath}/DenoRuntime.ts`, `${copyDirPath}/DenoRuntime.ts`);

// The compiler travels with the bundle: rollup inlines the tsgo client's
// JavaScript, so what has to be copied is the reactor it loads and the
// declarations that describe it. This used to copy TypeScript's own
// `typescript.js` and `typescript.d.ts` out of node_modules, which nothing has
// read since the compiler stopped being an npm package.
fileSystem.copySync(`${folderPath}/typescript.wasm`, `${copyDirPath}/typescript.wasm`);
copyDeclarationsForDeno("./lib/tsNamespace.d.ts", `${copyDirPath}/tsNamespace.d.ts`);
for (const filePath of declarationFilesUnder("./lib/tsgo"))
  copyDeclarationsForDeno(filePath, `${copyDirPath}/tsgo/${path.relative(path.join(folders.common, "lib/tsgo"), filePath).replace(/\\/g, "/")}`);
fileSystem.writeFileSync(
  `${copyDirPath}/typescript.d.ts`,
  `// Generated by scripts/buildDeno.ts. DO NOT EDIT.\n\nimport * as ts from "./tsNamespace.d.ts";\nexport { ts };\n`,
);
fileSystem.copySync(`./lib/ts-morph-common.d.ts`, `${copyDirPath}/ts_morph_common.d.ts`);
fileSystem.writeFileSync(`${copyDirPath}/mod.ts`, `// @deno-types="./ts_morph_common.d.ts"\nexport * from "./ts_morph_common.js";\n`);
fileSystem.writeFileSync(
  `${copyDirPath}/deno.json`,
  JSON.stringify(
    {
      "name": "@ts-morph/common",
      "version": packageJson.version,
      "license": "MIT",
      "exports": "./mod.ts",
      "imports": {
        "@std/fs": "jsr:@std/fs@1",
        "@std/path": "jsr:@std/path@1",
      },
    },
    null,
    2,
  ) + "\n",
);

const finalDeclFile = project.addSourceFileAtPath(`${copyDirPath}/ts_morph_common.d.ts`);
updateOnlyModuleSpecifiers(finalDeclFile);
finalDeclFile.saveSync();

function updateTypeScriptImportsExports(file: tsMorph.SourceFile) {
  const localNames = new Set<string>();
  for (const statement of file.getStatements()) {
    if (!Node.isExportDeclaration(statement) && !Node.isImportDeclaration(statement))
      continue;
    const moduleSpecifierValue = statement.getModuleSpecifierValue();
    if (moduleSpecifierValue === "typescript" || moduleSpecifierValue === "./typescript") {
      statement.setModuleSpecifier("./typescript.js");

      // support ES modules
      if (Node.isImportDeclaration(statement)) {
        if (statement.getNamespaceImport() != null) {
          // move this to the top
          file.insertStatements(0, `// @deno-types="./typescript.d.ts"\nimport { ts } from "./typescript.js";`);
          statement.remove();
          continue;
        }

        // inline the named imports
        const namedImports = statement.getNamedImports();
        // replace the named imports with variable declarations
        file.insertStatements(statement.getChildIndex(), writer => {
          for (const namedImport of namedImports) {
            writeImportAsVarStmt(writer, {
              localName: namedImport.getAliasNode()?.getText() ?? namedImport.getName(),
              name: namedImport.getName(),
            });
          }
        });
        statement.remove();
      } else {
        // make the export declaration have some leading variable declarations, then remove the module specifier
        const namedExports = statement.getNamedExports();
        file.insertStatements(statement.getChildIndex(), writer => {
          for (const namedExport of namedExports) {
            writeImportAsVarStmt(writer, {
              localName: namedExport.getName(),
              name: namedExport.getName(),
            });
          }
        });
        statement.removeModuleSpecifier();
      }
    }
  }

  function writeImportAsVarStmt(writer: tsMorph.CodeBlockWriter, importDecl: { localName: string; name: string }) {
    if (localNames.has(importDecl.localName))
      return;

    localNames.add(importDecl.localName);
    writer.writeLine(`const ${importDecl.localName} = ts.${importDecl.name};`);
  }
}

/**
 * Rewrites the declaration file's specifiers for Deno, which wants an extension.
 *
 * `./typescript` is the `ts` namespace and has no JavaScript behind it any more,
 * so it points straight at the declaration file rather than at a `.js` with a
 * `@deno-types` comment above it. `./tsgo/*` is the vendored client.
 */
function updateOnlyModuleSpecifiers(file: tsMorph.SourceFile) {
  for (const statement of file.getStatements()) {
    if (!Node.isExportDeclaration(statement) && !Node.isImportDeclaration(statement))
      continue;
    const moduleSpecifierValue = statement.getModuleSpecifierValue();
    if (moduleSpecifierValue === "typescript" || moduleSpecifierValue === "./typescript")
      statement.setModuleSpecifier("./typescript.d.ts");
    else if (moduleSpecifierValue?.startsWith("./tsgo/"))
      statement.setModuleSpecifier(moduleSpecifierValue + ".d.ts");
  }
}

/**
 * Copies a declaration file, giving every relative specifier in it an extension.
 *
 * Deno resolves a specifier as written, where node and a bundler will try
 * extensions for it, so `"../enums/scriptKind.enum"` has to become
 * `"../enums/scriptKind.enum.d.ts"` on the way across.
 */
function copyDeclarationsForDeno(fromPath: string, toPath: string) {
  const text = fileSystem.readFileSync(fromPath);
  fileSystem.mkdirSync(path.dirname(toPath));
  fileSystem.writeFileSync(
    toPath,
    text.replace(/((?:from|import)\s*\(?\s*["'])(\.{1,2}\/[^"']+?)(["'])/g, (match, before, specifier, after) =>
      specifier.endsWith(".d.ts") || specifier.endsWith(".js") ? match : `${before}${specifier}.d.ts${after}`),
  );
}

/** Every `.d.ts` under `dirPath`, recursively. */
function declarationFilesUnder(dirPath: string): string[] {
  const result: string[] = [];
  for (const entry of fileSystem.readDirSync(path.resolve(dirPath))) {
    if (entry.isDirectory)
      result.push(...declarationFilesUnder(entry.name));
    else if (entry.name.endsWith(".d.ts"))
      result.push(entry.name);
  }
  return result;
}
